version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: myfronts
      POSTGRES_USER: docker   
      POSTGRES_PASSWORD: docker 
    ports:
      - 6500:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data  

volumes:
  postgres-data:
