version: '3.8'

services:
  postgres:
    container_name: postgresql_myfronts
    image: postgres:latest
    environment:
      POSTGRES_DB: myfronts
      POSTGRES_USER: admin  
      POSTGRES_PASSWORD: admin
    ports:
      - 6332:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data  

volumes:
  postgres-data: